### PR TITLE
Support for rotated sprites in Texture Packer

### PR DESCRIPTION
**Pull request by EskemaGames**

### CODE REVIEW

**Comment by EskemaGames** [comment]
Let me know if this works :)

**Comment by prime31** [comment]
I just pulled your branch and cherry picked the last commit. all set now.

**Comment by nsxdavid** [comment]
Doesn't appear your cherry picking worked.  Code for rotated TP sprites is not in the code anywhere.

**Comment by prime31** [comment]
The rotated sprite support was temporarily nixed. It only worked if
you never rotated a sprite. It needs a rewrite and I haven't gotten to
it yet.

Mike

On Nov 26, 2011, at 7:34 PM, David Whatley
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
Yeah, I see now that it was done by rotating the sprite rather than swapping the UV coordinates.  Boo.

**Comment by EskemaGames** [comment]
The code for rotated sprites works expect for panels, I didn't modified that part yet. To avoid messing with the main branch I've created my own branch to support those rotated sprites. And yes it was done rotating the sprite rather that UV swap, but hey David, the code is there, you can do the modifications by yourself :)

**Comment by nsxdavid** [comment]
I looked into changing that to just manage the UVs differently, but unfortunately even though I think this is the 'correct' way to do it, the way UV information is represented and propagated through the system prior to becoming actual UV values on verticies makes this a non-trivial change.  

Seems as though rotation of the sprites would be wrong because it would conflict with other sprite rotation operations.  But I've not looked into it to know this for a fact.

**Comment by prime31** [comment]
I was thinking rotating would be done like the original implementation
but then all future rotations need to the that into account. If the
initial rotation was say 20 degrees querying for the current rotation
would still return 0 (currentRotation - initialRotation) and rotating
by 45 degrees would result in an actual rotation of 45 +
initialRotation.

Mike

On Nov 27, 2011, at 1:06 PM, David Whatley
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
The term "rotated" is probably a poor choice as it makes one think that the sprite can be arbitrarily rotated by Texture Packer (or, at best, one of 4 orientations).  But that's not what it means.  As it works on rects, there are only two orientations... thus why rotated is a bool.  The "rotation" is always a swap of UV.

In fact, if you look at other implementations of TexturePacker control files/textures, such as Cocos2D-iPhone, you'll find that they just swap the UV and its done.

**Comment by prime31** [comment]
Interesting. That is indeed much more simple to implement. I hadn't
looked into the details of rotated sprites seeing as how I haven't yet
needed then. That makes it a much easier job of properly adding then
(not just applying a rotation).

Mike

On Nov 27, 2011, at 1:14 PM, David Whatley
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
Right.  In fact, the whole point of "rotated" is that it gives Texture Packer attempt to pack things in tighter... sometimes significantly tighter... on the atlas if some images can be "rotated" to be "on their side".  So it's generally a simple thing to support.

The term 'rotated' comes from the user-facing view of what its doing in the Texture Packer GUI.  Carrying that terminology along through the fnt file is both convenient and unfortunate since the world implies much more than it what its doing.

**Comment by capitaljmedia** [comment]
Does anyone know if this feature was ever added? It would be great to be able to use rotated textures from texturepacker.

**Pull request closed without merging**
