### PR TITLE
Fixed a typo bug that was causing vertical scrollable containers to erro...

### PR DESCRIPTION
**Pull request by acron0**
...r when dragged passed their bottom-most control

As you can see from the code, it's a small one :)

### CODE REVIEW

**Comment by prime31** [comment]
Not quite the right solution. That would only work with vertical containers and then subsequently break horizontal ones. I just pushed a proper fix.

**Comment by acron0** [comment]
Ah, cool. Team effort ;)

**Comment by nsxdavid** [comment]
Hey, I wanted to bring something to your attention.  At one of the talks
today by Goggle, they called you guys out by name to see if you were in the
audience.  Apparently you are doing something incorrectly in your IAP
plugin that they wanted to bring to your attention.  The effect is that
some percentage of transactions will not complete (and I saw that once
myself in testing actually).

Another of your licensees (Simon, I think was his name) is going to be
writing you with more details as he was present when that happened.  Just
in case he doesn't get to you, I wanted to pass along what I knew of it.  I
have a meeting with a guy from Google Marketplace and can get a tech
contact for you from them if you don't get this figured out before then.

David

On Mon, Mar 5, 2012 at 2:20 PM, Antony <
reply@reply.github.com

**Comment by acron0** [comment]
You probably want to send this directly to Mike...

**Comment by prime31** [comment]
David,

Oddly enough a Google engineer looked at our source code a couple
weeks ago and said it was solid as a rock. I'd love to hear any info
at all about this so do forward anything you have over.

Mike

On Mar 7, 2012, at 12:24 AM, David Whatley
reply@reply.github.com
wrote:

**Pull request closed without merging**
