### PR TITLE
Various fixes and small additions

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
- Cleaned up UISlider and UIProgressBar for more intuitive feedback.
- Updated shaders with fog fixes and tighter alpha testing.
- Updated UIAnimation with option to use realtimeSinceStartup and realChain method.
- Added onTouchUp event to UIButton
- Added UILanguageManager - based on Eskema's code

### CODE REVIEW

**Comment by FrittenKeeZ** [comment]
UILanguageManager is based on static language handling with support for multiple languages and language files.
Default language is English with file postfix EN - eg. menuText_EN.txt

Adding a new language

``` C#
if (!UILanguageManager.HasLanguage("Danish"))
{
    UILanguageManager.AddLanguage("Danish", "DA");
}
```

Loading a language manager for a specific file

``` C#
UILanguageManager languageManager = UILanguageManager.GetManager("menuText");
```

Removing a language manager for a specific file

``` C#
UILanguageManager.RemoveManager("menuText");
```

Listening for language changed event

``` C#
UILanguageManager.onLanguageChanged += OnLanguageChanged;
```

Changing language

``` C#
UILanguageManager.Language = "Danish";
```

Getting translation from language manager instance

``` C#
string playText = languageManager["play"];
```

Getting a list of all languages

``` C#
string[] languages = UILanguageManager.GetLanguages();
```

**Comment by acron0** [comment]
Ahh, I was looking at integrating something similar to this. Brilliant addition.

**Comment by FrittenKeeZ** [comment]
Which parts? :)

**Comment by acron0** [comment]
The language manager, sorry :)

**Comment by FrittenKeeZ** [comment]
Small changes to UILanguageManager to reflect the parsing changes from #67.

**Comment by FrittenKeeZ** [comment]
I've checked my commits a few times now and I can't find any problems with them, so unless someone protest I'll merge them tomorrow since I submitted them 2 weeks ago, and we need to continue so we can upgrade to 3.5.

**Comment by acron0** [comment]
Nope, all seems good.

**Pull request merged**
