### PR TITLE
Ghost joystick

### PR DESCRIPTION
**Pull request by yuriks**
A few bugfixes to the UIGhostJoystick I contributed a while back.

### CODE REVIEW

**Comment by yuriks** [comment]
That was quick. :) Thanks.

**Comment by derkoi** [comment]
What does the ghost joystick do please?

**Comment by yuriks** [comment]
Instead of always being visible on-screen, you define a touch area rect for it, and when you touch somewhere inside that rect it appears centered where you first touched, until you release, when it disappears again.

**Comment by derkoi** [comment]
Ah lovely! Like the joystick in Shadowgun?

**Pull request merged**
