### PR TITLE
Correction for relative positioning and anchoring

### PR DESCRIPTION
**Pull request by nsxdavid**
Since the refactor of positioning... anchoring and relative positioning has been broken for the right and bottom.

For example: 

``` C#
sprite.positionFromBottomRight(0,0);
```

Would move the sprite too far and not be visible at all on screen; where one expects it to be visible and anchored to the bottom right of the screen.

None of the demo scenes that use any right/bottom positioning are working correctly.

This commit fixes this problem by reworking the logic in IPositionablePositioningExtensions.cs : refreshPosition().

Notes:
- This also introduces what I believe to be the expected behavior that if you are positioning a sprite relative to a parent, then the percentages are relative to the parent as well.  For example, if I position to the bottom left but with 25% offset, it would move 25% the width of its parent.  Originally it was the screen, which didn't seem to make any sense or be useable for anything in this context.  Pixel offsets still work the same as they are absolute.
- There may be other issues with parenting propagation elsewhere in the code when it comes to animation, for example.  I've not looked into this, nor tested this as its unrelated parts of the code.  My thinking is that if this was wrong, other things might be wrong too.
- All the demo scenes now work correct as far as relative positioning goes.  However Kitchen Sink still has an error on startup which seems related to the original refactoring but is an entirely different bug not related to this code change.
- Even though this code works, the choice of where I put my support methods may not match the intended pattern as it relates to, say, the UIRelative class.  Too keep it simple and obvious I did all my work in one file, so this might need some methods moved around for architectural purposes.

### CODE REVIEW

**Comment by nsxdavid** [comment]
Note that I did let a Debug.Log() slip in there.  Remove at will. :D

**Comment by FrittenKeeZ** [comment]
The relative positioning refers to percentages of Screen width and height, using UIRelative methods, in order to maintain backwards compatibility since the naming of methods are the same.

I just tested out the positioning from bottom right, and I don't have any problems with, neither with parented objects.

I have not tested my code on the test scenes, but I can do that and check for weird behaviour. Animation has been updated in regards to scaling and auto repositioning.

**Comment by FrittenKeeZ** [comment]
I just noticed prime had changed some code in the original files which breaks the intended behaviour!

**Comment by nsxdavid** [comment]
Not sure... I understand your comments.  You first say it isn't broken (but I assure you it is... and its far from subtle!).  My code fixes it, though it may still not be exactly as intended.  

As for the particulars of my implementation: The % of parent is the only thing that makes sense.  % of the screen size when relative to a child is of limited usefulness.  One wants to generally say "half way into this panel" when a control is a child of a panel, etc.  A button in a panel would seldom want to offset itself based on the size of the screen... which might be anything.

**Comment by FrittenKeeZ** [comment]
What I'm saying with my comments, is that the changes I submitted didn't break the whole thing as you mentioned, but the changes prime made afterwards did, of which I have no control.

I understand your views in regards to the relative offset from the parent, but right now I'm pretty sure you've broken the reliability when changing parents. That's why I kept it based on the screen width/height as it won't change.

**Comment by prime31** [comment]
I have been mostly out of commission due to a project so I haven't gotten to go through all the changes line by line. In hindsight I should have pulled all the new stuff into a branch but then it might not have been looked at by anyone. The new positioning changes do appear to work as planned though I havent tested fully or with parent swaps. The original set of changes totally broke the demo scenes which is why adding the width/height back in occurred. That fixed all the demo scenes so I assumed it was an accidental omission unless I didn't understand the whole idea behind the changes. Was the UIRelative class intended to only be used internally and all positioning modifications would then go though the iPositionableExtensions?

**Comment by FrittenKeeZ** [comment]
Yes, that was the original intend as I didn't test it using the demo scenes, just local testing.
I do have an idea for implementing the relative positioning based on the parents dimensions instead of just the screen, but that will take a little while.

**Comment by prime31** [comment]
Aha. If that is the case (UIRelative is intended to only be used internally) perhaps it should be moved to an internal, sealed class then the demo scenes can be modified to work the new way.

**Comment by FrittenKeeZ** [comment]
That would probably be the best idea to avoid confusion later on.

**Comment by nsxdavid** [comment]
As a side note, the Kitchen Sink still has some other error in.  Just run it and it'll give an error.  I think it's related to the refactoring, but haven't delved into too too see what is going on.

**Comment by prime31** [comment]
I am out of commission due to a pile of projects and a bathroom repair that has my home with no shower/toilet for the next 2 weeks. Once I get a few minutes back I'll dig through all the changes.

**Comment by nsxdavid** [comment]
It seems there are other things not right either.  For example, create some text... parent it to another object, anchor it to the bottom right.  Now change the text (using the UITextInstance's .text field).  The text will change but suddenly it's in the upperleft of the screen.  I'm still working on it, but I can't seem to get the text to correctly reposition after that no matter what I do either.

EDIT: Easier repo.  Create some text, anchor bottom right of the screen.  Now update the text, it'll jump to the upper left and you can't get it to move from there.  Still trying to figure out whats going on.

**Comment by FrittenKeeZ** [comment]
I found the problem and am in the process of fixing it.

**Comment by FrittenKeeZ** [comment]
Fixes have been added to request #45.

**Pull request merged**
