### PR TITLE
Re-corrected positioning with right and bottom

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Offset should not be subtracted from screen height/width, it is actually accounted for in the positioning.

### CODE REVIEW

**Comment by nsxdavid** [comment]
My version of fixing this problem did not change this method because these methods may be used elsewhere where the code as written being the intended behavior.  From their documentation, it would seems that is what is intended.

Further it doesn't address the relative positioning vs. the parent problem as my fix does.

**Comment by FrittenKeeZ** [comment]
I rewrote them for this whole thing, so I'm pretty sure what my intended behaviour was with them, and I checked if code with similar names were used elsewhere to ensure I wouldn't break anything.

The relative positioning in regards to the parent isn't what I would call a fix, rather a thinking.

**Comment by nsxdavid** [comment]
Ah okay... now I'm on the same page.  So yeah that method should be fixed to work as expected.  I should have looked closer at who authored the original changes!  I'd have to look if it would break my changes since they were already merged into the main.  It might take some work to make it compatible and still maintain my other behavior...

Speaking of which, I agree the relative positioning in regards to the parent is a separate issue entirely, and is really a design thing.  Though related enough, and linked code wise enough, it got kind of tangled up in all this.

So switching gears a bit to make the case of this way of thinking:
1. The API use to be entirely relative to the screen only.  With the introduction of parents, this made the screen the default root of the scene graph for UIToolkit.  So it follows that the percentage positioning would be relative to the parent.  As all pre-parenting code was against the screen anyway, this is backwards compatible.
2. Your change made the behavior of methods like positionFromBottomRight() work relative to the parent (or the screen if no parent).  So it is reasonable that the offset parameters would also likewise be relative to the parent (or the screen if no parent).  Otherwise it is inconsistent with itself.
3. Lastly, from a utility stand point, relative to parent is what you really want.  With the introduction of parent objects, the user will be wanting to not only anchor relative to a parent (like a panel or something) but also specify an offset (say to push a control away from the border a little bit).  If the offset is specified as a % of the screen, the results could be inconsistent on different screen sizes which is the opposite of the intention of using relative %s in the first place.... where one is trying to keep things proportionately the same.  I say "could be" here because it depends on how the parent object is designed to react to screen size changes.  But if the % is of the parent, it would behave consistently regardless.

As an anecdotal datapoint, my current project UI is all wired back up with my version of these changes and the relative to parent of the offsets is used heavily.  Not once did I need, or can even think of, a reason yet where I'd want that offset to be relative to the screen except when the parent is the screen.  Such a circumstance may exist, but I'm hard pressed to think of one so far.

**Comment by FrittenKeeZ** [comment]
After thinking about it I do agree it makes most sense to have the relative positioning be that of the parent's dimension, but in order to make that work properly when changing parents, they auto adjustment of anchor information needs to be updated as well, otherwise that part will remain broken.

**Comment by nsxdavid** [comment]
I've put in a fix for this in my local branch, but not tested.  I have already submitted another patch for a null ref when you try to unparent.

**Comment by nsxdavid** [comment]
The text breaking is caused because when text changes the glyph sprites are rebuilt in worldspace irrespective of their parent.  I've fixed this in my local branch but some issues remain.  Right alignment is not aligning properly.  This may be unrelated to what I've done, but I want to get it right before pushing.

**Comment by FrittenKeeZ** [comment]
Just spotted that one as well, but can't say it's my doing :)

I've fixed the positioning of the glyph sprites but will check with alignment as well.

**Comment by FrittenKeeZ** [comment]
Okay, I've located the issue regarding alignment and know what to do to fix it.
I will do it on my own branch so it won't interfere with what you've changed (including the relative parent width positioning).

**Comment by prime31** [comment]
I am getting a 404 trying to pull from your repo...

**Comment by nsxdavid** [comment]
This change still does not handle the % offsets being from the parent rather than the screen, unless I'm missing something.

Is that intended to be a separate change?

**Comment by FrittenKeeZ** [comment]
Yes, it is intended to be in a separate change.
I'll have a look at the demo scenes firstly so they work properly.

**Comment by nsxdavid** [comment]
How about I just add a parent argument to the UIRelative methods and have them do parent-or-screen-if-null in each?

**Comment by FrittenKeeZ** [comment]
You could, but the problem of auto re-anchoring on parent change will still be broken.
I have a solution for it in my head, so just have a little patience :)

**Comment by nsxdavid** [comment]
Well the idea of open source is you don't have to be the guy who fixes everything. :)

I have my code as yours now, but I added the change for % of parent as above.  It works for everything I've been able to try it on so far.  I don't understand the issue with reparenting.  If you are working on it, then I'll just leave my local code like this so I can unblock while you conjure up a proper solution.

**Comment by FrittenKeeZ** [comment]
That should do it. Demo scenes are working and relative positioning is done based on parent's width and height.

**Comment by nsxdavid** [comment]
Sweeeeeeet!  Will check this out shortly.

**Comment by nsxdavid** [comment]
Works pretty well, but found this issue:

If you have an object that's scaled, then make another object as a child and position it... works as expected (the child is scaled by its parent).  If later you do another reposition pixelsFromRight(), it'll do the reposition but the scale of the child will be wrong (unscaled).   Might just be the pixelsFromRight() sort of operation that's causing it in general, haven't dug into it yet.

**Comment by nsxdavid** [comment]
On further examination, the issue is not what I thought per se.  It looks as though objects are getting some sort of stray scaling at times when parented (even though neither they nor their parent is scaled).  It is not consistent, so I'm not sure what's going on yet.

**Comment by nsxdavid** [comment]
... and there are other issues.  In how animation is handled with this stuff.  And in text still.  I'm going to try and come up with repos if I can figure out what's really going on.

The text one I can identify: It is not purging unused glyph sprites if you replace the text with a shorter string.

**Comment by nsxdavid** [comment]
Okay, so here's the issue with text:

There's a couple little bugs in the mechanism that figures out how many sprites to remove if the new string is shorter than the current number of sprites.  These were fixed elsewhere, but got reverted in these commits.  The first is a < vs. a >, the other is a one off on the loop which causes it to remove one too few sprites.

However, the really crazy bug is this:  When each of the unneeded sprites are removed the UISpriteManager's vertex mesh gets the associtated verts set to 0.  This is good.  Later, in DrawText the very first thing it does now is textInstance.position = Vector3.zero.  Doing this sets off a series of delegate callbacks for all of its sprites so they can update their position.  And in doing so, ends up filling back in the vertex array with the previous values.  So when the mesh is updated it has a mix of the new and old text even though the other sprites are gone.

This suggests that the onTransformChanged() delegate is not being cleared when the sprite is removed.  I'll track that down next, but this should be enough info for you to quickly correct these errors.

Adding:

```
    sprite.parentUIObject = null; // remove any delegate callbacks, etc.
```

To UISpriteManager.cs : removeSprite() fixes that issue.

Correct code for the removal logic in UITextInstance text property set:

```
        // cleanse our textSprites of any excess that we dont need

        if (_text.Length < textSprites.Count) {

            for (var i = textSprites.Count - 1; i >= _text.Length; i--) {

                var sprite = textSprites[i];

                textSprites.RemoveAt(i);

                _parentText.manager.removeElement(sprite);

            }

        }
```

**Comment by nsxdavid** [comment]
Text as a child of another object does not reposition when the parent moves.

This is because the UITextInstance does not have an implication of transformChanged() that does anything.

I'm pretty sure what it should do is call transformChanged() on all its sprites.

Though I've not tested this, I believe that even UISprite does not have a sufficient implementation of transformChanged() to handle nesting parent->child more than one deep.  It too would need to propogate transformChanged() notifications to its children.  UISprites do not know what children they have, but I believe the transform's children is valid for this now.

**Comment by FrittenKeeZ** [comment]
I also wonder why the transformChanged method isn't calling its base, which would seem logical when doing inheritance.

**Comment by FrittenKeeZ** [comment]
In regards to the stray scaling, have you updated your UIObject? The problem I had was the anchor update was done before the actual objects transform had been re-parented, so it messed up big time when scaling.

**Comment by FrittenKeeZ** [comment]
David, I fixed the issue for nested text and found out that UITouchableSprite prevented the transformChanged event from happening, which pretty much affects everything nested in buttons.

**Comment by nsxdavid** [comment]
Confirming that these changes seem to work in my (limited) test scenarios.  Although, that being said, I've restructured a lot of my use-case to work around issues here and there.

Might I suggest someone create a set of regression tests?  This is getting sufficiently complex now and full of side-effects that each change needs to be vetted in some manner for unintended consequences.

**Comment by nsxdavid** [comment]
Just a note that I'm seeing odd behavior on the Z component of objects.  Not sure if its related to anchoring, parenting or animation.  I'm going to drill into it, but may not get into it until tonight.  This is causing things to suddenly sort behind other things when they should not.  Its consistent, so I should be able to isolate it.

**Comment by FrittenKeeZ** [comment]
Although I haven't quite tested it, I'm pretty sure it the refreshPosition method. I'll just upload that change and you can check if it fixed it.

**Comment by nsxdavid** [comment]
I've not tested everything here, but these changes seem okay.  There is still an issue where changing the text on a UITextInstance can cause the Z of the verts to be wrong.  In my the UITextInstance is a child of a UISprite.  Changing the text will yeild different Z values for the verts (until it sorts wrong).  Looking into it.

**Comment by nsxdavid** [comment]
The issue is that each glyph sprite is being constructed/updated with a depth value, but since these are now specified in local space, this means any depth is being "double applied" so to speak.  The code needs to not  use depth when making these sprites, just use 0 for depth.  The proper depth will be applied because they are children of the UITextInstance which is where the real depth is now maintained.

**Comment by FrittenKeeZ** [comment]
Nicely spotted David :)

**Comment by nsxdavid** [comment]
These changes look good.

**Comment by FrittenKeeZ** [comment]
I'm just thinking if I should make a new branch from the latest updates of the master, so there won't be any conflicts?

**Comment by prime31** [comment]
If everything is looking solid we an pull it into the mainline then
start up a new branch for rotation and trimming.

Mike

On Dec 3, 2011, at 3:04 AM, FrittenKeeZ
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
I agree.  I think this is ready for mainline.  It is certainly far better than what is there now which is pretty badly broken (as all these changes can attest!).

**Comment by prime31** [comment]
Can you make a new, clean pull request so that I can grab it and stick
it in the mainline?

Mike

On Sat, Dec 3, 2011 at 11:56 AM, David Whatley
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
I've merged all this into a Positioning branch on this repo, nice and clean.  I made a pull request to merge into master.

Not sure if you want me to do these merges into master, or do pull requests.  I opted for the more conservative approach until I hear otherwise. :)

**Comment by prime31** [comment]
Feel free to merge it in!

Mike

On Dec 3, 2011, at 10:39 PM, David Whatley
reply@reply.github.com
wrote:

**Pull request closed without merging**
