### PR TITLE
Add userData to UIObject

### PR DESCRIPTION
**Pull request by yuriks**
Modified version of pull request #55

### CODE REVIEW

**Comment by FrittenKeeZ** [comment]
I concur with this change... Was really questioning the need for additional parameters in the constructors...

**Comment by yuriks** [comment]
Any comments on merging this change?

**Comment by ricardojmendez** [comment]
Any particular reason why this is on hold?  I'd like to update my UIFramework branch from the main repo, but don't want to have to repeatedly patch this on top.

**Comment by yuriks** [comment]
Oops, just realized some changes I pushed to my repo also got included here... better fix that.

ricardojmendez: I don't know either. I assumed everyone was taking a vacation but there were other pull reqs merged in the meantime.

**Comment by FrittenKeeZ** [comment]
Sorry for being so late with this.
I hate quite a few corrections here and there from the project I did back in December, so I'll sort those out tonight along with the other pull requests.

**Pull request merged**
