### PR TITLE
Upgraded the project to 3.5

### PR DESCRIPTION
**Pull request by acron0**

### CODE REVIEW

**Comment by acron0** [comment]
Any chance of this pull?

**Comment by FrittenKeeZ** [comment]
Sorry, I was away for a few days. Can you check for conflicts after I've merged the other requests so we can get this step completed?

**Comment by acron0** [comment]
Yep, no problem

**Comment by acron0** [comment]
Seems totally fine :)

**Comment by FrittenKeeZ** [comment]
Just one thing, why did you out comment the co routines in the text demo scenes?

**Comment by acron0** [comment]
D'oh. I'll resubmit.

**Pull request closed without merging**
