### PR TITLE
Replaced Hashtable references on UISpriteManager for IDictionary

### PR DESCRIPTION
**Pull request by ricardojmendez**
Referring to the dictionaries by the interface instead of the specific Hashtable class allows people to change their deserialization implementation from MiniJson to any other, like JsonFx, which might return a different IDictionary implementation.

### CODE REVIEW

**Comment by acron0** [comment]
Is this a good thing though? There are merits in forcing users to adhere to a single format; it's less confusing for a start.

**Comment by ricardojmendez** [comment]
It's still a single format: where this would help is when you want to remove MiniJson to avoid having two Json libraries knocking around in your project (with possibly inconsistent behavior).      Replacing MiniJson is not drag-and-drop, and requires you to write your own MiniJsonStub with the methods that UIToolkit references, so chances are someone who goes through that can fathom the implications.  

This changeset help ensure that the process is a one-time change, and that it it won't have to be re-done with every UIToolkit update.

**Comment by FrittenKeeZ** [comment]
Honestly I'm not really sure this is a problem, since UIToolkit's implementation is tied to TexturePacker's export format. I could definitely see the issue if everything was decoupled, but currently it's not.

**Comment by ricardojmendez** [comment]
TexturePacker export format is Json.  What this allows you to do is change the library you use to read that Json.  It is not intended to change the sprite description specification.

**Comment by acron0** [comment]
In fairness, the change is pretty trivial and has no negative effects so why not...

**Pull request merged**
