### PR TITLE
UITextInstance changes to be added to UIAbstractContainer

### PR DESCRIPTION
**Pull request by getluky**
See commit notes for details.

### CODE REVIEW

**Comment by prime31** [comment]
I'm not so sure this is the right solution. UIAbstractContainer should never know or care what a UITextInstance is. It breaks encapsulation and poses a host of potential problems. The first I noticed is that what if the UITextInstance changes? It is quite common for test to change (scores, lives, health, etc) and that would cause this setup to break.

Perhaps a better solution would be to have UITextInstance be a subclass of UIObject using it's Transform as a proxy of sorts. When the transform changes (position, rotation or scale would all work through the transform) it could trigger a relayout of the actual sprites that the UITextInstance manages. This would allow it to work seamlessly with containers, the animation system, parenting and possibly even positioning (through IPositionable). Perhaps UITextInstance can be promoted in the process so that it relies less on it's parent UIText.

**Comment by getluky** [comment]
Can't really argue with you. Converting UITextInstance to UIObject is definitely the direction I'd go if I had more time. It would also require changing the collection type of UIAbstractContainer to UIObject from UISprite.

Believe it or not, I actually made this hack work with text changes (a requirement for my setup) by detaching and reattaching all of the UISprites to the abstract container as the parent UI object. It required fiddling with the transform properties ahead of time, and it works with translation and scaling, but I haven't checked rotation. Getting that far, I learned a lot about the setup, and could definitely see that just subclassing UIObject would be the right approach, but I ran way over the time I allocated to get this working, so I might have to wait a while before I can afford more time to get back to it.

**Comment by getluky** [comment]
Took a deeper look at this today. Would you be opposed to bringing properties like width, height, positioning, scale, anchor point, etc. into UIObject to make it so that UIAbstractContainer's can just be changed to holding UIObjects (instead of UISprites)?

**Comment by prime31** [comment]
Perhaps if UIObject implemented IPositionable directly and containers took in child UIObjects it could work. At quick glance that might just do the trick with the least amount of changes.

**Comment by getluky** [comment]
Yes, I think this might be the way to go. Then, I'd probably set the parent UIObject of all the text sprites to the UITextInstance. I'll try to give it a shot soon. Thanks!

**Comment by andykorth** [comment]
I found that since UIAbstractContainers could only have UISprites as children, I wasn't able to nest containers. Usually this is how I do layouts, for example two horizontally laid out rows of UI elements within a vertically laid out container. 

I also ran into the desire of adding UITextInstances to containers to organize my layout as well...

Any progress on this, or additional thoughts?

**Comment by getluky** [comment]
I haven't been available to make this change yet. We discussed a favorable solution above if you want to try it yourself.

**Comment by prime31** [comment]
This will probably only make sense to getluky as he has dug into this the most but I will mention it here as a sort of documentation.

The plan from up above was not fully sound. I rearranged some stuff and make UITextInstance be a subclass of UIObject. UIObject now implements IPositionable (and throws an exception if it isn't override in a subclass). This gets one piece of the puzzle done and allows UITextInstances to be animated with the standard animation method.

The next thing needed in UITextInstance is a width/height implementation that is smart (only calculates once and clears when text changes). From their, to get containers to work with UIObject's the hidden property needs to either go down to UIObject (might make sense) or to IPositionable (might not make as much sense). Once that is done everything should play nice and UITextInstance will work like any other element.

And finally (and most importantly) UITextInstance needs to learn to reuse its UISprites. That will speed it up drastically if it is changing a lot (timers, points, etc)

**Pull request closed without merging**
