### PR TITLE
2 misc. changes again

### PR DESCRIPTION
**Pull request by yuriks**
Sorry for the pull request spam. I was in a hurry earlier and wanted to push the changes out. We can see how that turned out. :P

### CODE REVIEW

**Comment by nsxdavid** [comment]
Cool, will look this over in a bit and merge (if no one else has by then).  Sure this is the one? :)

**Comment by nsxdavid** [comment]
Since you are adjusting the feel of scrolling... think you could tackle getting bounce in there as well?

**Comment by yuriks** [comment]
I took a look at doing that, but didn't right now due to time
constrains. I'll probably be looking at that again later, so if no one
does it in the meantime I'll do it.

-- yuriks // Yuri K. Schlesner
My new mail address: yuriks@yuriks.net

On Fri, Dec 30, 2011 at 5:21 PM, David Whatley
reply@reply.github.com
wrote:

**Comment by yuriks** [comment]
I had messed up the previous commits (didn't test after doing the merge and had some conflicts unresolved.) So I cancelled the pull requests, overwrote the master on my fork and openend another request. I'm not sure what happened? Did you merge the wrong pull req. by accident?

**Comment by nsxdavid** [comment]
Its the same pull as far as I know.  Go look and make sure it didn't 
bork what you were intending to put up there.

David Whatley
Critical Thought Games, LLC

**Pull request merged**
