### PR TITLE
Added StringData to ITouchable

### PR DESCRIPTION
**Pull request by ricardojmendez**
Hello,

Here's a minor change I did to ITouchable which you may find useful.
- Added StringData to ITouchable, so that if multiple buttons share the
  same handler they can be easily identified, or their specific data used
  without having to evaluate the button instance (for example, when you
  have multiple buttons to load levels).
- Expanded constructors of the various classes implementing ITouchable
  and their descendants so we can pass stringData as a parameter.

Cheers!

### CODE REVIEW

**Comment by nsxdavid** [comment]
This is a good idea, though generally this sort of thing is done with a generic user pointer (in C# that'd be a System.Object reference).  This lets one attach anything, strings included.

Any reason why not to do it that way?

**Comment by ricardojmendez** [comment]
No particular reason - good point. I didn't immediately think of doing it that way since I was getting acquainted with the library, but will likely change it soon to a TouchedData.

**Comment by nsxdavid** [comment]
UserData is a more common term since  TouchData implies something else.

**Comment by yuriks** [comment]
I'm not sure all the additional parameters on constructors are needed either. You usually have to set other properties of the button anyway, so I don't think adding a parameter for this is justified.

Also, I'm kinda needing this, so I'm gonna go ahead and do another pull request with the fixes. :)

**Comment by ricardojmendez** [comment]
Closing, since we have the changes above by yuriks.

**Pull request closed without merging**
